export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_FAVOURITE = "ADD_FAVOURITE"
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE"
export const CHECK_FAVOURITE = "CHECK_FAVOURITE"
export const GET_FAVOURITES = "GET_FAVOURITE"

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';